### ISSUE TITLE
Clear button does not trigger (onRemove) event

### ISSUE THREAD

**Issue by oguzeker** [aberezkin/ng2-image-upload#110]
When **"Clear"** button is pressed **(onRemove)** event does not get triggered. So, uploaded images does not get deleted.

**Current code seen in my project:**
<img width="525" alt="screen shot 2017-07-18 at 13 55 40" src="https://user-images.githubusercontent.com/9478905/28313895-2bae3d8c-6bc1-11e7-9823-1299805a732c.png">

**Should be like:**
<img width="526" alt="screen shot 2017-07-18 at 13 56 33" src="https://user-images.githubusercontent.com/9478905/28313905-3882d928-6bc1-11e7-89bf-e496c4d7e954.png">

**Important:** I have installed ng2-image-upload through the following command:

> npm install angular2-image-upload --save

However, the codes of ng2-image-upload which is in my project now seems slightly different from the original code in github. 
**_e.g._** The event **(removed)** in github corresponds as **(onRemove)** event in my project.

<img width="522" alt="screen shot 2017-07-18 at 14 07 49" src="https://user-images.githubusercontent.com/9478905/28314303-a4084196-6bc2-11e7-8c55-02aac0e5ac12.png">

**Comment by UncleDave** [comment]
We currently have an issue with the wrong readme being displayed on github.

Our default branch is `development`, whereas the latest release is on `master`, by default the repo will show you the `development` readme, which is unreleased - #104 

This issue was fixed in 0.6.5, but it would appear we've had an issue publishing it.
@aberezkin I think it's probably worth grabbing the 0.6.5 tag, manually bumping the version to 0.6.6 and releasing again.

**Comment by aberezkin** [comment]
Done
