### ISSUE TITLE
Error with latest Angular2 version

### ISSUE THREAD

**Issue by flintcreativestudio** [aberezkin/ng2-image-upload#19]
Hi Arkadii,

Updated Angular2 to latest build (2.3.1)  and am getting this error on compile.

> Error encountered resolving symbol values statically. Calling function 'ImageUploadModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /website.com/src/app/app.module.ts, resolving symbol AppModule in /website.com/src/app/app.module.ts

Any clue what could be wrong?

**Comment by aberezkin** [comment]
Hi Flint,

Hmmm, it all seems very strange. You're not the only one reporting this issue look at #13. I suppose you're using Angular CLI too. It's great that you figured out that the angular update caused this problem because all my attempts to reproduce this error failed. I'll try to do it with the latest build and figure out what's wrong and if I won't I'm planning to reach out someone from the angular team to help me to solve this.

The problem is that I don't have time for that now because it final exams month at my university and I need to concentrate on my studies. I can take care of this issue the next Saturday. Sorry for that.

And the last moment, are you using CLI. If so I'll mark this as duplicate of #13 and close.

**Comment by flintcreativestudio** [comment]
Ok good luck with the exams. I'll try to find out whats wrong too, otherwise my project can't launch.. :)

**Comment by f1k2c** [comment]
i also having the same error
