### ISSUE TITLE
angular-cli 1.0.0.beta.28.3 ImageUploadModule Problem

### ISSUE THREAD

**Issue by caglarturkurka** [aberezkin/ng2-image-upload#25]
I use angular-cli for developing angular 2 application.But I have a problem about ImageUploadModule and I know that this problem was sent before.But I did not solve this problem.Please help me about this problem.Thank you

```
ERROR in Error encountered resolving symbol values statically. Calling function 'ImageUploadModule', function calls are not supported. Consider replacing the functio
n or lambda with a reference to an exported function
```

**Comment by briangardner** [comment]
I'm having the same issue.

**Comment by pisix** [comment]
I'm having the same issue

**Comment by lutsifer** [comment]
Same, anyone solution?

**Comment by kevincaicedo** [comment]
I am also having the same problem some solution ?

**Comment by salttechno** [comment]
Has anyone got the solution for this?

**Comment by lutsifer** [comment]
besides switching package - no. But in general there is no good file upload for angular 2. There is always something that is not exactly as it has to be...

**Comment by chakermellek** [comment]
As a workaround solution, you can set the provider yourself in the root module.

`import {BrowserModule} from '@angular/platform-browser';
import {NgModule} from '@angular/core';

import {AppComponent} from './app.component';
import {AppRoutingModule} from "./app-routing.module";
import {ImageUploadModule} from "angular2-image-upload";
import {ImageService} from "angular2-image-upload/lib/image.service";


@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,

    AppRoutingModule,
    PagesModule
  ],
  providers: [
    {provide: ImageService, useClass: ImageService}
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
}
`

Then in the module where you want to upload images, you have to import the ImageUploadModule.

PS: The ImageUploadModule.forRoot() causes the problem, don't add it to the AppModule until this problem is fixed.

**Comment by pisix** [comment]
@chakermellek pls Can you provide a plunker of your workaround ? 
Thanks .

**Comment by AlanCrevon** [comment]
Same problem here. 
@chakermellek : i can't make your workaround work. Could you give more infos ?
